# BUSINESS

In [1]:
import pandas as pd

business_df = pd.read_csv('neo4j_csvs/business.csv')

/var/folders/r3/89932hws5rg2xwsqck66y26r0000gp/T/ipykernel_5166/1321394659.py:3: DtypeWarning: Columns (91,92,94,95,96,97,98,99,100) have mixed types. Specify dtype option on import or set low_memory=False.
  business_df = pd.read_csv('neo4j_csvs/business.csv')

In [2]:
business_df[business_df[business_df.columns[91:]].notna().any(axis='columns')][business_df.columns[91:]]

,attributes_Open24Hours,attributes_RestaurantsCounterService,attributes_AgesAllowed,attributes_DietaryRestrictions_dairy-free,attributes_DietaryRestrictions_gluten-free,attributes_DietaryRestrictions_vegan,attributes_DietaryRestrictions_kosher,attributes_DietaryRestrictions_halal,attributes_DietaryRestrictions_soy-free,attributes_DietaryRestrictions_vegetarian
1450,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3735,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4774,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6034,NaN,NaN,21plus,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6610,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
146171,NaN,NaN,allages,NaN,NaN,NaN,NaN,NaN,NaN,NaN
146496,NaN,NaN,allages,NaN,NaN,NaN,NaN,NaN,NaN,NaN
147578,NaN,NaN,NaN,False,True,False,False,False,False,True
148988,NaN,NaN,21plus,NaN,NaN,NaN,NaN,NaN,NaN,NaN
149306,NaN,NaN,allages,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
business_df[business_df['attributes_Open24Hours'].notna()][business_df.columns[91:]]

,attributes_Open24Hours,attributes_RestaurantsCounterService,attributes_AgesAllowed,attributes_DietaryRestrictions_dairy-free,attributes_DietaryRestrictions_gluten-free,attributes_DietaryRestrictions_vegan,attributes_DietaryRestrictions_kosher,attributes_DietaryRestrictions_halal,attributes_DietaryRestrictions_soy-free,attributes_DietaryRestrictions_vegetarian
1450,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4774,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6610,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9451,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11880,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19351,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20891,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24885,False,True,NaN,True,True,True,False,False,True,True
28436,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30361,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30574,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31641,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33720,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37381,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39548,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39945,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42413,False,True,NaN,True,True,True,False,False,True,True
52907,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65954,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66831,False,True,NaN,True,True,True,False,False,True,True
69013,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75430,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76984,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81015,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83076,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91559,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93292,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94624,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95163,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98706,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102809,False,NaN,NaN,False,False,True,False,False,False,True
107431,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110601,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119195,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
124809,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
125697,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
129721,True,True,NaN,False,False,True,False,False,False,True
133326,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
143028,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
for column in business_df.columns:
    print(f'Per la colonna {column} i valori non na sono {len(business_df[business_df[column].notna()])}')

Per la colonna :LABEL i valori non na sono 150243
Per la colonna business_id:ID i valori non na sono 150243
Per la colonna name i valori non na sono 150243
Per la colonna address i valori non na sono 145117
Per la colonna city i valori non na sono 150243

KeyboardInterrupt:

In [ ]:
business_df[business_df['hours_Monday'] == '0:0-0:0']

,:LABEL,business_id:ID,name,address,city,state,postal_code,latitude,longitude,stars,...,attributes_Open24Hours,attributes_RestaurantsCounterService,attributes_AgesAllowed,attributes_DietaryRestrictions_dairy-free,attributes_DietaryRestrictions_gluten-free,attributes_DietaryRestrictions_vegan,attributes_DietaryRestrictions_kosher,attributes_DietaryRestrictions_halal,attributes_DietaryRestrictions_soy-free,attributes_DietaryRestrictions_vegetarian
1,Business,e1a902b3497f013225f4691a03c73a5a,The UPS Store,87 Grasso Plaza Shopping Center,Affton,MO,63123,38.551126,-90.335695,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Business,97afb2dd310b6f8dc03661b02e238f44,Sonic Drive-In,615 S Main St,Ashland City,TN,37015,36.269593,-87.058943,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Business,157f5d3a749df51fb2aad74b847bec8f,Famous Footwear,"8522 Eager Road, Dierbergs Brentwood Point",Brentwood,MO,63144,38.627695,-90.340465,2.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Business,adf64e8146738216c0254e000104ff40,Sonic Drive-In,2312 Dickerson Pike,Nashville,TN,37207,36.208102,-86.768170,1.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Business,52c05d51afefedf1239001b0a88c2a35,Arizona Truck Outfitters,625 N Stone Ave,Tucson,AZ,85705,32.229872,-110.972342,4.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150224,Business,78b8a641701e1143f4316ccf1b2b4da7,Dutch Bros Coffee,1181 N Milwaukee St,Boise,ID,83704,43.615401,-116.284689,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150225,Business,8ff52776e781f588f68501a7f5463394,Savaya Coffee Market,11177 N Oracle Rd,Oro Valley,AZ,85737,32.409552,-110.943073,4.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150228,Business,89c93a2c4d1794a3a148ac342811a021,La Quinta by Wyndham NW Tucson Marana,6020 West Hospitality Rd,Tucson,AZ,85743,32.358587,-111.093308,2.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150232,Business,d9b77f4bee2703acefba3539f8b0c038,St. Vincent Heart Center of Indiana,10580 N Meridian St,Indianapolis,IN,46290,39.939489,-86.159502,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150236,Business,0d244d82faf7a344ec4dbea5b91c46fd,The Plum Pit,4405 Pennell Rd,Aston,DE,19014,39.856185,-75.427725,4.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# da droppare hours_
# questi sotto si possono droppare con piÃ¹ tranquillitÃ  in quanto sono anche delle categorie
# Per la colonna attributes_DietaryRestrictions_dairy-free i valori non na sono 30
# Per la colonna attributes_DietaryRestrictions_gluten-free i valori non na sono 30
# Per la colonna attributes_DietaryRestrictions_vegan i valori non na sono 30
# Per la colonna attributes_DietaryRestrictions_kosher i valori non na sono 30
# Per la colonna attributes_DietaryRestrictions_halal i valori non na sono 30
# Per la colonna attributes_DietaryRestrictions_soy-free i valori non na sono 30
# Per la colonna attributes_DietaryRestrictions_vegetarian i valori non na sono 30
# Per la colonna attributes_AgesAllowed i valori non na sono 129 (altre categorie lo includono)

In [ ]:
# Per la colonna attributes_Open24Hours i valori non na sono 39 veramente poco valorizzato
# Per la colonna attributes_RestaurantsCounterService i valori non na sono 19 veramente poco valorizzato

In [ ]:
new_columns = [c for c in business_df.columns if not c.startswith('hours_') and len(business_df[business_df[c].notna()]) > 1000]

In [ ]:
len(new_columns)

84

In [ ]:
business_df['is_open'].value_counts()

1    119603
0     30640
Name: is_open, dtype: int64

In [ ]:
# altre colonne da eliminare = :LABEL, name, address, city, state, postal_code
#  per la posizione ci affidiamo solo a latitudine e longitudine
# categories sono una relazione

In [ ]:
new_columns.remove(":LABEL")
new_columns.remove("name")
new_columns.remove("address")
new_columns.remove("city")
new_columns.remove("state")
new_columns.remove("postal_code")
new_columns.remove("categories")

In [ ]:
business_df = business_df[new_columns]

In [ ]:
business_df[business_df[business_df.columns[6:]].isna().all(axis='columns')] # comunque utili perchÃ© collegano persone e recensioni

,business_id:ID,latitude,longitude,stars,review_count,is_open,attributes_ByAppointmentOnly,attributes_BusinessAcceptsCreditCards,attributes_BikeParking,attributes_RestaurantsPriceRange2,...,attributes_Corkage,attributes_BYOBCorkage,attributes_HairSpecializesIn_straightperms,attributes_HairSpecializesIn_coloring,attributes_HairSpecializesIn_extensions,attributes_HairSpecializesIn_africanamerican,attributes_HairSpecializesIn_curly,attributes_HairSpecializesIn_kids,attributes_HairSpecializesIn_perms,attributes_HairSpecializesIn_asian
7,52089d3eabd5e01def1dbd58371fd535,27.766590,-82.732983,3.5,5,1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,b84fa11605acdd39d6340ebabaf22e8d,29.981183,-90.254012,3.5,14,1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,00e9a293efa268552d3ba1c071b2eb6d,40.273493,-74.987496,5.0,15,1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,5695efa60b7d3cc2d7bc3a183e9248cc,39.915478,-75.016973,5.0,5,1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,6f836275fc1cfb1e166ae4add2bd756a,39.969300,-86.165002,5.0,7,1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150197,8f2ecc32a7880b1f27cd160faa3b3c3d,30.022340,-90.052255,4.0,5,1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150199,a14231611eb1dfef3e6ffb26934ea0d5,39.631153,-86.085342,4.0,17,1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150205,30b22766a0965b000632028bbeb94bf9,40.021346,-74.932089,3.5,5,1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150229,a88d09d968d3de8a0707fbb7e6f04d0e,53.513215,-113.328680,5.0,5,1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150234,708eb8521840f8969e7fe9b0372e7a1a,39.857700,-74.987230,4.0,5,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
print(business_df.dtypes)

business_id:ID                                   object
latitude                                        float64
longitude                                       float64
stars                                           float64
review_count                                      int64
                                                 ...
attributes_HairSpecializesIn_africanamerican     object
attributes_HairSpecializesIn_curly               object
attributes_HairSpecializesIn_kids                object
attributes_HairSpecializesIn_perms               object
attributes_HairSpecializesIn_asian               object
Length: 77, dtype: object

In [ ]:
# MATCH (n:Business)--(c:Category) WITH c.name as name, collect(COALESCE(n.attributes_ByAppointmentOnly, "null")) as allapp RETURN name, size([x in allapp WHERE x = "null"]) as null1, size([x in allapp WHERE x = "True"]) as True1, size([x in allapp WHERE x = "False"]) as False1, toFloat(size([x in allapp WHERE x = "null"]))/ size(allapp) as ratio ORDER BY ratio DESC

In [ ]:
# Missing values logic
# attributes_BusinessAcceptsCreditCards  -> true
# others = -1

In [ ]:
business_df['attributes_BusinessAcceptsCreditCards'].fillna(True, inplace=True)

In [ ]:
print(business_df.dtypes)

business_id:ID                                   object
latitude                                        float64
longitude                                       float64
stars                                           float64
review_count                                      int64
                                                 ...
attributes_HairSpecializesIn_africanamerican     object
attributes_HairSpecializesIn_curly               object
attributes_HairSpecializesIn_kids                object
attributes_HairSpecializesIn_perms               object
attributes_HairSpecializesIn_asian               object
Length: 77, dtype: object

In [ ]:
print(business_df['attributes_RestaurantsPriceRange2'].dtypes)

float64

In [ ]:
pd.get_dummies(business_df[['attributes_ByAppointmentOnly']])

        attributes_ByAppointmentOnly_False  attributes_ByAppointmentOnly_True
0                                        0                                  1
1                                        0                                  0
2                                        1                                  0
3                                        1                                  0
4                                        0                                  0
...                                    ...                                ...
150238                                   1                                  0
150239                                   0                                  0
150240                                   0                                  0
150241                                   0                                  0
150242                                   1                                  0

[150243 rows x 2 columns]

In [ ]:
for column in business_df.columns:
    print(f'{column} is a {business_df[column].dtype}')

business_id:ID is a object
latitude is a float64
longitude is a float64
stars is a float64
review_count is a int64
is_open is a int64
attributes_ByAppointmentOnly is a object
attributes_BusinessAcceptsCreditCards is a bool
attributes_BikeParking is a object
attributes_RestaurantsPriceRange2 is a float64
attributes_CoatCheck is a object
attributes_RestaurantsTakeOut is a object
attributes_RestaurantsDelivery is a object
attributes_Caters is a object
attributes_WiFi is a object
attributes_BusinessParking_garage is a object
attributes_BusinessParking_street is a object
attributes_BusinessParking_validated is a object
attributes_BusinessParking_lot is a object
attributes_BusinessParking_valet is a object
attributes_WheelchairAccessible is a object
attributes_HappyHour is a object
attributes_OutdoorSeating is a object
attributes_HasTV is a object
attributes_RestaurantsReservations is a object
attributes_DogsAllowed is a object
attributes_Alcohol is a object
attributes_GoodForKids is a object
attributes_RestaurantsAttire is a object
attributes_RestaurantsTableService is a object
attributes_RestaurantsGoodForGroups is a object
attributes_DriveThru is a object
attributes_NoiseLevel is a object
attributes_Ambience_romantic is a object
attributes_Ambience_intimate is a object
attributes_Ambience_touristy is a object
attributes_Ambience_hipster is a object
attributes_Ambience_divey is a object
attributes_Ambience_classy is a object
attributes_Ambience_trendy is a object
attributes_Ambience_upscale is a object
attributes_Ambience_casual is a object
attributes_GoodForMeal_dessert is a object
attributes_GoodForMeal_latenight is a object
attributes_GoodForMeal_lunch is a object
attributes_GoodForMeal_dinner is a object
attributes_GoodForMeal_brunch is a object
attributes_GoodForMeal_breakfast is a object
attributes_BusinessAcceptsBitcoin is a object
attributes_Smoking is a object
attributes_Music_dj is a object
attributes_Music_background_music is a object
attributes_Music_no_music is a object
attributes_Music_jukebox is a object
attributes_Music_live is a object
attributes_Music_video is a object
attributes_Music_karaoke is a object
attributes_GoodForDancing is a object
attributes_AcceptsInsurance is a object
attributes_BestNights_monday is a object
attributes_BestNights_tuesday is a object
attributes_BestNights_friday is a object
attributes_BestNights_wednesday is a object
attributes_BestNights_thursday is a object
attributes_BestNights_sunday is a object
attributes_BestNights_saturday is a object
attributes_BYOB is a object
attributes_Corkage is a object
attributes_BYOBCorkage is a object
attributes_HairSpecializesIn_straightperms is a object
attributes_HairSpecializesIn_coloring is a object
attributes_HairSpecializesIn_extensions is a object
attributes_HairSpecializesIn_africanamerican is a object
attributes_HairSpecializesIn_curly is a object
attributes_HairSpecializesIn_kids is a object
attributes_HairSpecializesIn_perms is a object
attributes_HairSpecializesIn_asian is a object

In [ ]:
# all dummies except
# business_id:ID
# latitude
# longitude
# stars
# review_count
# is_open
# attributes_BusinessAcceptsCreditCards
# attributes_RestaurantsPriceRange2

In [ ]:
float_columns = ['latitude', 'longitude', 'stars', 'review_count', 'is_open', 'attributes_BusinessAcceptsCreditCards', 'attributes_RestaurantsPriceRange2']
list_of_dummies_columns = list(set(business_df.columns) - set(['business_id:ID', *float_columns]))

In [ ]:
dummies = pd.get_dummies(business_df[list_of_dummies_columns])

In [ ]:
dummies

,attributes_CoatCheck_False,attributes_CoatCheck_True,attributes_AcceptsInsurance_False,attributes_AcceptsInsurance_True,attributes_Ambience_trendy_False,attributes_Ambience_trendy_True,attributes_WheelchairAccessible_False,attributes_WheelchairAccessible_True,attributes_RestaurantsTableService_False,attributes_RestaurantsTableService_True,...,attributes_RestaurantsAttire_casual,attributes_RestaurantsAttire_dressy,attributes_RestaurantsAttire_formal,attributes_WiFi_free,attributes_WiFi_no,attributes_WiFi_paid,attributes_BestNights_thursday_False,attributes_BestNights_thursday_True,attributes_BusinessParking_street_False,attributes_BusinessParking_street_True
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,1,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
4,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150238,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
150239,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
150240,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
150241,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
150242,0,0,0,0,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,1,0

In [ ]:
floats = business_df[float_columns].fillna(-1).astype(float)

In [ ]:
business_features = pd.concat([floats, dummies], axis=1).astype(float)

In [ ]:
business_features

,latitude,longitude,stars,review_count,is_open,attributes_BusinessAcceptsCreditCards,attributes_RestaurantsPriceRange2,attributes_CoatCheck_False,attributes_CoatCheck_True,attributes_AcceptsInsurance_False,...,attributes_RestaurantsAttire_casual,attributes_RestaurantsAttire_dressy,attributes_RestaurantsAttire_formal,attributes_WiFi_free,attributes_WiFi_no,attributes_WiFi_paid,attributes_BestNights_thursday_False,attributes_BestNights_thursday_True,attributes_BusinessParking_street_False,attributes_BusinessParking_street_True
0,34.426679,-119.711197,5.0,7.0,0.0,1.0,-1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,38.551126,-90.335695,3.0,15.0,1.0,1.0,-1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,32.223236,-110.880452,3.5,22.0,0.0,1.0,2.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
3,39.955505,-75.155564,4.0,80.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
4,40.338183,-75.471659,4.5,13.0,1.0,1.0,-1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150238,53.468419,-113.492054,3.0,13.0,1.0,1.0,3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
150239,36.115118,-86.766925,4.0,5.0,1.0,1.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
150240,39.908707,-86.065088,3.5,8.0,1.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
150241,38.782351,-89.950558,4.0,24.0,1.0,1.0,4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
150242,27.771002,-82.394910,4.5,9.0,1.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

In [ ]:
import torch

In [ ]:
business_ids = business_df['business_id:ID']

In [ ]:
business_tensor_features = torch.tensor(business_features.values, dtype=torch.float64)

In [ ]:
torch.save(business_tensor_features, 'preprocessed/business_feature.pt')

In [ ]:
business_ids.to_csv('preprocessed/business_ids.csv', index=False)

# USER

In [ ]:
import pandas as pd

user_df = pd.read_csv('neo4j_csvs/user.csv')

/var/folders/r3/89932hws5rg2xwsqck66y26r0000gp/T/ipykernel_3190/3844060479.py:3: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  user_df = pd.read_csv('neo4j_csvs/user.csv')

In [ ]:
user_df

,user_id:ID,name,review_count,yelping_since,useful,funny,cool,elite,friends,fans,...,compliment_profile,compliment_cute,compliment_list,compliment_note,compliment_plain,compliment_cool,compliment_funny,compliment_writer,compliment_photos,:LABEL
0,qVc8ODYU5SZjKXVBgXdI7w,Walker,585,2007-01-25 16:47:26,7217,1259,5994,2007,"NSCy54eWehBJyZdG2iE84w, pe42u7DcCH2QmI81NX-8qA...",267,...,55,56,18,232,844,467,467,239,180,User
1,j14WgRoU_-2ZE1aw1dXrJg,Daniel,4333,2009-01-25 04:35:42,43091,13066,27281,"(2009, 2010, 2011, 2012, 2013, 2014, 2015, 201...","ueRPE0CX75ePGMqOFVj6IQ, 52oH4DrRvzzl8wh5UXyU0A...",3138,...,184,157,251,1847,7054,3131,3131,1521,1946,User
2,2WnXYQFK0hXEoTxPtV2zvg,Steph,665,2008-07-25 10:41:00,2086,1010,1003,"(2009, 2010, 2011, 2012, 2013)","LuO3Bn4f3rlhyHIaNfTlnA, j9B4XdHUhDfTKVecyWQgyA...",52,...,10,17,3,66,96,119,119,35,18,User
3,SZDeASXq7o05mMNLshsdIA,Gwen,224,2005-11-29 04:38:33,512,330,299,"(2009, 2010, 2011)","enx1vVPnfdNUdPho6PH_wg, 4wOcvMLtU6a9Lslggq74Vg...",28,...,1,6,2,12,16,26,26,10,9,User
4,hA5lMy-EnncsH4JoR-hFGQ,Karen,79,2007-01-05 19:40:59,29,15,7,NaN,"PBK4q9KEEBHhFvSXCUirIw, 3FWPpM7KU1gXeOM_ZbYMbA...",1,...,0,0,0,1,1,0,0,0,0,User
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1987892,fB3jbHi3m0L2KgGOxBv6uw,Jerrold,23,2015-01-06 00:31:31,7,0,0,NaN,NaN,0,...,0,0,0,0,0,0,0,0,0,User
1987893,68czcr4BxJyMQ9cJBm6C7Q,Jane,1,2016-06-14 07:20:52,0,0,0,NaN,NaN,0,...,0,0,0,0,0,0,0,0,0,User
1987894,1x3KMskYxOuJCjRz70xOqQ,Shomari,4,2017-02-04 15:31:58,1,1,0,NaN,NaN,0,...,0,0,0,0,0,0,0,0,0,User
1987895,ulfGl4tdbrH05xKzh5lnog,Susanne,2,2011-01-14 00:29:08,0,0,0,NaN,NaN,0,...,0,0,0,0,0,0,0,0,0,User
1987896,wL5jPrLRVCK_Pmo4lM1zpA,Isa,2,2020-12-19 02:32:39,0,0,0,NaN,NaN,0,...,0,0,0,0,0,0,0,0,0,User

In [ ]:
for column in user_df.columns:
    print(f' {column} has  {len(user_df[user_df[column].notna()])} values not na')

 user_id:ID has  1987897 values not na
 name has  1987860 values not na
 review_count has  1987897 values not na
 yelping_since has  1987897 values not na
 useful has  1987897 values not na
 funny has  1987897 values not na
 cool has  1987897 values not na
 elite has  91198 values not na
 friends has  1109346 values not na
 fans has  1987897 values not na
 average_stars has  1987897 values not na
 compliment_hot has  1987897 values not na
 compliment_more has  1987897 values not na
 compliment_profile has  1987897 values not na
 compliment_cute has  1987897 values not na
 compliment_list has  1987897 values not na
 compliment_note has  1987897 values not na
 compliment_plain has  1987897 values not na
 compliment_cool has  1987897 values not na
 compliment_funny has  1987897 values not na
 compliment_writer has  1987897 values not na
 compliment_photos has  1987897 values not na
 :LABEL has  1987897 values not na

In [ ]:
for column in user_df.columns:
    print(f'{column} is a {user_df[column].dtype}')

user_id:ID is a object
name is a object
review_count is a int64
yelping_since is a object
useful is a int64
funny is a int64
cool is a int64
elite is a object
friends is a object
fans is a int64
average_stars is a float64
compliment_hot is a int64
compliment_more is a int64
compliment_profile is a int64
compliment_cute is a int64
compliment_list is a int64
compliment_note is a int64
compliment_plain is a int64
compliment_cool is a int64
compliment_funny is a int64
compliment_writer is a int64
compliment_photos is a int64
:LABEL is a object

In [ ]:
user_features = user_df[['review_count', 'useful', 'funny', 'cool', 'fans', 'average_stars', 'compliment_hot', 'compliment_more', 'compliment_profile', 'compliment_cute', 'compliment_list', 'compliment_note', 'compliment_plain', 'compliment_cool', 'compliment_funny', 'compliment_writer', 'compliment_photos']].astype(float)

In [ ]:
user_tensor_features = torch.tensor(user_features.values, dtype=torch.float64)

In [ ]:
user_tensor_features

tensor([[5.8500e+02, 7.2170e+03, 1.2590e+03,  ..., 4.6700e+02, 2.3900e+02,
         1.8000e+02],
        [4.3330e+03, 4.3091e+04, 1.3066e+04,  ..., 3.1310e+03, 1.5210e+03,
         1.9460e+03],
        [6.6500e+02, 2.0860e+03, 1.0100e+03,  ..., 1.1900e+02, 3.5000e+01,
         1.8000e+01],
        ...,
        [4.0000e+00, 1.0000e+00, 1.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [2.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [2.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00]], dtype=torch.float64)

In [ ]:
torch.save(user_tensor_features, 'preprocessed/user_feature.pt')
user_df['user_id:ID'].to_csv('preprocessed/user_ids.csv', index=False)

# REVIEW

In [ ]:
import pandas as pd

review_df = pd.read_csv('neo4j_csvs/review.csv')

In [ ]:
review_df

,:LABEL,review_id:ID,stars:float,useful:float,funny:float,cool:float,text,date
0,Review,14b7eabcf7250cac8884af3677c0b8af,3.0,0,0,0,If you decide to eat here just be aware it is ...,2018-07-07 22:09:11
1,Review,0baa75e21e14c71f057e9ad453082867,5.0,1,0,1,I've taken a lot of spin classes over the year...,2012-01-03 15:28:18
2,Review,af722966fda3d69d36a0ac9de0292e51,3.0,0,0,0,Family diner. Had the buffet. Eclectic assortm...,2014-02-05 20:30:30
3,Review,50d32c50663bd2b424f57561a09cbfda,5.0,1,0,1,Wow! Yummy different delicious. Our favori...,2015-01-04 00:01:03
4,Review,a3383e594a74583aabcda6de8e3cb8a8,4.0,1,0,1,Cute interior and owner (?) gave us tour of up...,2017-01-14 20:54:15
...,...,...,...,...,...,...,...,...
6989553,Review,94e309064b7859538c514528e80db157,5.0,1,2,1,Latest addition to services from ICCU is Apple...,2014-12-17 21:45:20
6989554,Review,2d0aa703beebc1996c58711a6e4b04e3,5.0,2,1,2,This spot offers a great affordable east weeke...,2021-03-31 16:55:10
6989555,Review,eaac0ea0e1fb9aab851008575a49c98c,4.0,1,0,0,This Home Depot won me over when I needed to g...,2019-12-30 03:56:30
6989556,Review,0dab15fea0a38d0f706afeed71945194,5.0,1,0,0,For when I'm feeling like ignoring my calorie-...,2022-01-19 18:59:27
6989557,Review,c8f2c9be46a45c9378399c7afd1066af,3.0,10,3,7,Located in the 'Walking District' in Nashville...,2018-01-02 22:50:47

In [ ]:
review_features = review_df[['stars:float', 'useful:float', 'funny:float', 'cool:float']].astype(float)

In [ ]:
review_tensor_features = torch.tensor(review_features.values, dtype=torch.float64)

In [ ]:
review_tensor_features

tensor([[ 3.,  0.,  0.,  0.],
        [ 5.,  1.,  0.,  1.],
        [ 3.,  0.,  0.,  0.],
        ...,
        [ 4.,  1.,  0.,  0.],
        [ 5.,  1.,  0.,  0.],
        [ 3., 10.,  3.,  7.]], dtype=torch.float64)

In [ ]:
review_df['review_id:ID'].to_csv('preprocessed/review_ids.csv', index=False)

# TIP

In [1]:
import pandas as pd

tip_df = pd.read_csv('neo4j_csvs/tip.csv')

In [2]:
tip_df

,tip_id:ID,:LABEL,text,date,compliment_count
0,cfcd208495d565ef66e7dff9f98764da,Tip,Avengers time with the ladies.,2012-05-18 02:17:21,0
1,c4ca4238a0b923820dcc509a6f75849b,Tip,They have lots of good deserts and tasty cuban...,2013-02-05 18:35:10,0
2,c81e728d9d4c2f636f067f89cc14862c,Tip,It's open even when you think it isn't,2013-08-18 00:56:08,0
3,eccbc87e4b5ce2fe28308fd9f2a7baf3,Tip,Very decent fried chicken,2017-06-27 23:05:38,0
4,a87ff679a2f3e71d9181a67b7542122c,Tip,Appetizers.. platter special for lunch,2012-10-06 19:43:09,0
...,...,...,...,...,...
908873,8f46946986ed283cc02fbca21f7b97cb,Tip,Disappointed in one of your managers.,2021-09-11 19:18:57,0
908874,98cd2178e85f0f3ad347f403decf43d3,Tip,Great food and service.,2021-10-30 11:54:36,0
908875,d5dccb85561e35c20f3add3eac8522af,Tip,Love their Cubans!!,2021-11-05 13:18:56,0
908876,d07d908f0a182ea84cd0bb027f9c8b1b,Tip,Great pizza great price,2021-11-20 16:11:44,0
908877,fa994d34ccade73821d84b1bb308715f,Tip,Food is good value but a bit hot!,2021-12-07 22:30:00,0

In [3]:
tip_df.fillna('', inplace=True)

In [4]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

tokenizer = AutoTokenizer.from_pretrained("LiYuan/amazon-review-sentiment-analysis")
model = AutoModelForSequenceClassification.from_pretrained("LiYuan/amazon-review-sentiment-analysis")

In [5]:
inputs = tokenizer("Hello world!", return_tensors="pt")
outputs = model(**inputs)

In [6]:
outputs.logits

tensor([[-1.1885, -2.0125, -1.2764,  0.5061,  3.3115]],
       grad_fn=<AddmmBackward0>)

In [7]:
from datasets import Dataset
dataset = Dataset.from_pandas(tip_df[['text']])
dataset.map(lambda examples: model(**tokenizer(examples["text"], padding=True, return_tensors="pt")), batched=True, batch_size=256)

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Map:   0%|          | 0/908878 [00:00<?, ? examples/s]

KeyboardInterrupt:

In [ ]:
outputs

SequenceClassifierOutput(loss=None, logits=tensor([[-1.1885, -2.0125, -1.2764,  0.5061,  3.3115]],
       grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)